# Generated by Django 4.1 on 2022-08-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('tcuenta_id', models.IntegerField(blank=True, db_column='TCuenta_id', null=True)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('cuenta_id', models.AutoField(db_column='Cuenta_id', primary_key=True, serialize=False)),
                ('numcuenta', models.IntegerField(db_column='NumCuenta')),
                ('monto', models.IntegerField(db_column='Monto')),
                ('tipo_operacion', models.TextField(db_column='Tipo_Operacion')),
                ('hora', models.TextField(db_column='HORA')),
            ],
            options={
                'db_table': 'Movimientos',
                'managed': True,
            },
        ),
    ]
