# Generated by Django 4.1 on 2022-08-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocuenta',
            fields=[
                ('tcuenta_id', models.AutoField(db_column='TCuenta_id', primary_key=True, serialize=False)),
                ('tcuenta_tipo', models.TextField(db_column='TCuenta_tipo')),
            ],
            options={
                'db_table': 'TipoCuenta',
                'managed': True,
            },
        ),
    ]
