# Generated by Django 4.1 on 2022-08-14 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_tipocuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tcuenta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.tipocuenta'),
        ),
    ]
