# Generated by Django 4.1 on 2022-08-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_tipoclientes_tcliente_limite_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.IntegerField(db_column='TipoCliente'),
        ),
    ]
