# Generated by Django 4.1 on 2022-08-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_alter_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('direccion_id', models.AutoField(db_column='Direccion_id', primary_key=True, serialize=False)),
                ('calle', models.TextField(db_column='Calle')),
                ('numero', models.TextField(db_column='Numero')),
                ('ciudad', models.TextField(db_column='Ciudad')),
                ('provincia', models.TextField(db_column='Provincia')),
                ('pais', models.TextField(db_column='Pais')),
            ],
            options={
                'db_table': 'Direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.BinaryField()),
                ('branch_name', models.TextField()),
                ('branch_address_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
    ]
