# Generated by Django 4.1 on 2022-08-29 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_direccion_sucursales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursales',
            name='branch_address_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clientes.direccion'),
        ),
    ]
