# Generated by Django 4.1 on 2022-08-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_direccionclientes_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionclientes',
            name='customer_id',
            field=models.IntegerField(default=1),
        ),
    ]
