# Generated by Django 4.1 on 2022-08-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0002_alter_prestamo_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='account_num',
            field=models.IntegerField(default=1),
        ),
    ]
