# Generated by Django 4.1 on 2022-08-29 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_alter_cuenta_tcuenta_id'),
        ('Prestamos', '0003_prestamo_account_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='account_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.cuenta'),
        ),
    ]
