# Generated by Django 4.1 on 2022-08-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoclientes',
            name='tcliente_limite_prestamo',
            field=models.IntegerField(db_column='TCliente_Prestamo', default=1),
            preserve_default=False,
        ),
    ]
