# Generated by Django 4.1 on 2022-08-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcastarjetas',
            fields=[
                ('ttarjetas_id', models.AutoField(db_column='TTarjetas_id', primary_key=True, serialize=False)),
                ('ttarjetas_marca', models.TextField(db_column='TTarjetas_Marca')),
            ],
            options={
                'db_table': 'MarcasTarjetas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('tarjetas_id', models.AutoField(db_column='Tarjetas_id', primary_key=True, serialize=False)),
                ('tarjeta_numero', models.TextField(db_column='Tarjeta_Numero', unique=True)),
                ('tarjeta_cvv', models.TextField(db_column='Tarjeta_CVV')),
                ('tarjeta_fecha_otorgamiento', models.TextField(db_column='Tarjeta_Fecha_Otorgamiento')),
                ('tarjeta_fecha_expiracion', models.TextField(db_column='Tarjeta_Fecha_Expiracion')),
                ('tarjeta_tipo', models.TextField(db_column='Tarjeta_tipo')),
                ('asignacion', models.TextField(db_column='Asignacion')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.cliente')),
                ('ttarjetas', models.ForeignKey(db_column='TTarjetas_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Tarjetas.marcastarjetas')),
            ],
            options={
                'db_table': 'Tarjetas',
                'managed': True,
            },
        ),
    ]
